### ISSUE TITLE
Deserialization throws when optional relationship is set to null at incoming JSON.

### ISSUE THREAD

**Issue by kczulko** [qvantel/jsonapi-scala#12]
Hi,

I found some deserialization issue. Is that expected behavior for null JSON value (data.relationships.foo === null) which should be deserialized into Option[ToOne[T]] ?

## Steps to reproduce

Create Option[ToOne[_]] relation like below:

```scala
import com.qvantel.jsonapi.{ApiRoot, ToOne, jsonApiResource, rawOne}
import spray.http.Uri.Path
import spray.json.DefaultJsonProtocol

object Main extends DefaultJsonProtocol {

  def main(args: Array[String]): Unit = {
    implicit val apiRoot: com.qvantel.jsonapi.ApiRoot = ApiRoot(Some(Path("/api")))

    @jsonApiResource final case class Foo(id: String)
    @jsonApiResource final case class Bar(id: String)
    @jsonApiResource final case class Baz(id: String, foo: Option[ToOne[Foo]], bar: Option[ToOne[Bar]])

    val result = rawOne(Baz("baz", None, Some(ToOne.loaded(Bar("bar")))))

    println { result.prettyPrint }

    val incomingJson =
      """
        |{
        |  "data": {
        |    "attributes": {
        |
        |    },
        |    "relationships": {
        |      "bar": {
        |        "data": {
        |          "type": "bars",
        |          "id": "bar"
        |        },
        |        "links": {
        |          "related": "/api/bazs/baz/bar"
        |        }
        |      },
        |      "foo": null
        |    },
        |    "links": {
        |      "self": "/api/bazs/baz"
        |    },
        |    "id": "baz",
        |    "type": "bazs"
        |  },
        |  "included": [{
        |    "type": "bars",
        |    "attributes": {
        |
        |    },
        |    "id": "bar",
        |    "links": {
        |      "self": "/api/bars/bar"
        |    }
        |  }]
        |}
      """.stripMargin

    import spray.json._

    val deserializedBaz = com.qvantel.jsonapi.readOne[Baz](incomingJson.parseJson.asJsObject)

    println { deserializedBaz }
  }
}
```

## Current behavior:

`main` method from above throws:

```
spray.json.DeserializationException: JSON object expected
	at spray.json.package$.deserializationError(package.scala:23)
	at spray.json.JsValue.asJsObject(JsValue.scala:36)
	at spray.json.JsValue.asJsObject(JsValue.scala:41)
	at com.qvantel.jsonapi.spray.Main$Baz$4$$anon$3.com$qvantel$jsonapi$spray$Main$Baz$4$$anon$3$$$anonfun$19(Main.scala:14)
	at scala.Option.flatMap(Option.scala:171)
	at com.qvantel.jsonapi.spray.Main$Baz$4$$anon$3.com$qvantel$jsonapi$spray$Main$Baz$4$$anon$3$$$anonfun$18(Main.scala:14)
	at scala.Option.flatMap(Option.scala:171)
	at com.qvantel.jsonapi.spray.Main$Baz$4$$anon$3.read(Main.scala:14)
	at com.qvantel.jsonapi.spray.Main$Baz$4$$anon$3.read(Main.scala:14)
	at com.qvantel.jsonapi.package$.readOne(package.scala:144)
	at com.qvantel.jsonapi.spray.Main$.main(Main.scala:60)
	at com.qvantel.jsonapi.spray.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

## Expected behavior.

Any JSON key under "relationships" section with `null` value should be properly deserialized into `Option[ToOne[_]]`.

## Additional info.

Reproduced at
```
commit 214c8af79388ed525c53ff05b4f871e7e5c1b8ba
Author: Aki Huttunen <aki.huttunen@qvantel.com>
Date:   Thu Jul 6 14:24:40 2017 +0300

    Add a way to differentiate no ids and empty list of ids on ToMany
    and PolyToMany. Fixes #8
```

In fact this relationships section deserializes properly:
```
"relationships": {
  "foo": {
    "data": null
  }
}
```

but `{ "foo": null }` is a valid JSON entry and should be properly deserialized when destination type was wrapped into `Option`.

**Comment by Doikor** [comment]
Fix will be published in 5.0.3 which should be out in ~30minutes or so.
